apiVersion: v1
kind: Service
metadata:
  name: pothen-esxes-k8s
  labels:
    name: pothen-esxes-k8s
spec:
  ports:
    - nodePort: 30164
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: pothen-esxes-k8s
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pothen-esxes-k8s
spec:
  selector:
    matchLabels:
      app: pothen-esxes-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: pothen-esxes-k8s
    spec:
      containers:
        - name: pothen-esxes-k8s
          image: pothen-esxes-k8s:1.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres_user
                  name: postgres-credentials
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
